apiVersion : apps/v1
kind: Deployment
metadata:
  name: delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery
  template:
    metadata:
      labels:
        app: delivery
    spec:
      containers:
        - name: delivery
          image: 879772956301.dkr.ecr.ap-northeast-2.amazonaws.com/test-product:latest
          ports:
            - containerPort: 8080
